### ISSUE TITLE
LTO9 support

### ISSUE THREAD

**Issue by fe0376** [cea-hpc/phobos#6]
how come the LTO9 is not in the tape_model supported list? in the phobos.conf it says:
 "supported_list = LTO5,LTO6,LTO7,LTO8,T10KB,T10KC,T10KD"
but also:
[tape_type "LTO9"]
drive_rw = LTO9_drive

when I use phobos tape add --type LTO9 it errors:
2024-01-03 17:04:19,045 <ERROR> invalid media tape model 'LTO9': Invalid argument
2024-01-03 17:04:19,046 <ERROR> SQL media request failed: Invalid argument
2024-01-03 17:04:19,046 <ERROR> Cannot issue set request (Invalid argument)

so is LTO9 supported or not?

**Comment by fe0376** [comment]
I added LTO9 to the tape type list and now it works.

**Comment by courrierg** [comment]
Hello @fe0376,

Thank you for your interest in Phobos. The technology supported by Phobos mostly depends on what LTFS supports.
You can find this list on the README of LTFS' github: https://github.com/LinearTapeFileSystem/ltfs

The configuration "supported_list" is simply for Phobos to know what technologies exist and what to look for in the configuration to assess the compatibility between tapes and drives. This can be updated as you did to add technologies that you want to use as long as LTFS support them.
